### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by BrandonCopley** [MadisonReed/usps-webtools#17]
It would be great if we could pass in a timeout parameter because this am I am seeing USPS calls taking forever and i'm not able to timeout the functions currently.

**Comment by BrandonCopley** [comment]
I have added this, but now we need to get this shoved up to NPM.

**Comment by divesnob** [comment]
merged PR and pushing to NPM

**Comment by divesnob** [comment]
npm just got updated with 0.0.11

-matt

Matt Darling
VP Engineering - Madison Reed
415.505.4623

500 Second Street, SF, CA 94107-1404

LIVE LIFE BRILLIANTLY | #BEBRILLIANT | MADISON-REED.com
<http://madison-reed.com/>
Facebook <https://www.facebook.com/MadisonReedLLB> | Pinterest
<http://www.pinterest.com/madisonreedllb/> | Instagram
<http://instagram.com/madisonreedllb> | Twitter
<https://twitter.com/madisonreedllb> | Google+
<https://plus.google.com/108491753835225258772/posts> | LinkedIn
<http://www.linkedin.com/company/madison-color> | YouTube
<http://www.youtube.com/user/MadisonReedVideos>
