### ISSUE TITLE
None of the tests are passing

### ISSUE THREAD

**Issue by peterhanneman** [MadisonReed/usps-webtools#21]
Have specified API key in each test file.  Have tried both HTTP production and HTTPS secure endpoints.  It would appear that the endpoints have changed as of 1/17 according to USPS website but still no dice after updating.

**Comment by divesnob** [comment]
Coming back to this issue.  If you replace the `##` in test files

```
var usps = new USPS({
  server: 'http://production.shippingapis.com/ShippingAPI.dll',
  userId: '##'
});
```

with your USPS userId, the tests will pass.
