### ISSUE TITLE
Major security issues

### ISSUE THREAD

**Issue by BrandonCopley** [MadisonReed/usps-webtools#23]
There are a few major security issues I found with this package that are super easy to fix:

**qs** needs to be upgraded to above 1.0.0 (1.0.0 and below are affected)
**request** needs to be upgraded to 2.78.0
**hawk** needs to be upgraded as well

**Comment by BrandonCopley** [comment]
Anything I can do to update this? - I can pull request it or I can help get this tested and pushed up to NPM. These issues should be fixed soon I believe.

**Comment by divesnob** [comment]
thanks @BrandonCopley - feel free to create a PR and we'll loop it in.

**Comment by BrandonCopley** [comment]
I have just created the PR.

**Comment by divesnob** [comment]
Addressed issue and pushed 0.2.1 up to npm.
