### ISSUE TITLE
Published version on NPM is broken

### ISSUE THREAD

**Issue by colinhemphill** [MadisonReed/usps-webtools#25]
The latest version on NPM is 0.2.2, and it's crashing.

```
TypeError: console.eyes is not a function
    at callUSPS (/myDirectory/node_modules/usps-webtools/src/usps.js:210:11)
```

There is, in fact, a line with `console.eyes()`. I see that this is no longer in source here on GitHub, but the current version on NPM is no good.

**Comment by divesnob** [comment]
Colin,

We were seeing 0.2.1 published on GitHub and npm.  We overwrote whatever
was up there with 0.2.3.

Neither our repo nor the code that we saw up there had console.eyes() on
line 210.

Please continue to let us know if you have any other issues with the module.

Thanks,

-matt

MATT DARLING

—

VP Engineering

Phone: 415.505.4623

Social: @MadisonReedLLB

Madison-Reed.com <http://www.madison-reed.com/>

MADISONREED®

**Comment by colinhemphill** [comment]
I had `"usps-webtools": "0.2.x"` in my package file, and 0.2.2 is what NPM pulled down as the latest version.

I'm now able to pull 0.2.3, and that's working for me. Thanks!
